# Model Hyperparameters
model:
  A: 30 # Angle dimension size (-15 to 15 degrees)
  D: 40 # Depth dimension size (0 to 20m)
  N: 40 # Sonar vector length
  M: 64 # Sonar feature vector dimension
  K: 256 # Fusion feature dimension
  H1: 64 # Parameter calibration MLP hidden layer 1
  H2: 32 # Parameter calibration MLP hidden layer 2
  C_in: 16 # 2D convolution input channels
  MAX_DEPTH: 20.0 # Maximum depth (meters)
  ANGLE_RANGE: 30.0 # Angle range (-15 to 15 degrees)

# Training parameters
training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 50
  lr_decay_factor: 0.5
  lr_patience: 5
  lambda_phys: 0.1 # Physical consistency loss weight
  lambda_ent: 0.01 # Entropy regularization weight

# Data augmentation parameters
augmentation:
  param_noise_std: 0.05
  sonar_noise_std: 0.02

# Dataset parameters
dataset:
  train_ratio: 0.8
  synthetic_samples: 2000
  noise_level: 0.1

